### ISSUE TITLE
Document how to fix python, and fix it

### ISSUE THREAD

**Issue by davclark** [dlab-projects/benten-config#10]
I needed to manually upload wheels for pip and setuptools into /lib64/python3.4/ensurepip/_bundle so that venv works.

**Comment by davclark** [comment]
Explanation / fix is [here](http://stackoverflow.com/a/33767179/468660). @Carpetfizz do you care about this? This might be a good task for you... for now I'm just encouraging continued use of conda. There are still bad problems with venv/virtualenvs like [this matplotlib issue](http://matplotlib.org/faq/virtualenv_faq.html).

**Comment by Carpetfizz** [comment]
Thanks Dav, we've been using conda so far and haven't had any problems.
I'll refer to this issue if we need to start using virtualenv/pip although
I doubt it.
